import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import Header from "../components/Header";
import styled from "styled-components";
import MembersList from "../components/MembersList";

export default function Home() {
  const AppContainer = styled.div`
    height: 100vh;
    overflow-y: scroll;
  `;
  const Main = styled.main`
    background-color: aliceblue;
    padding: 48px;
  `;
  const HeaderContainer = styled.div`
    position: sticky;
    top: 0;
    z-index: 10000000;
    background-color: rgba(255, 255, 255, 0.75);
    backdrop-filter: blur(4px);
  `;

  const Divider = styled.div`
    border: 1px #fff;
  `;

  // const Member = styled.div`
  //   width: 250px;
  //   height: 400px;
  //   -webkit-border-radius: 20px;
  //   -moz-border-radius: 20px;
  //   border-radius: 20px;
  //   background-color: white;
  //   -moz-box-shadow: 32px 36px 50px -51px rgba(0, 0, 0, 0.58);
  //   -webkit-box-shadow: 32px 36px 50px -51px rgba(0, 0, 0, 0.58);
  //   -ms-box-shadow: 32px 36px 50px -51px rgba(0, 0, 0, 0.58);
  //   box-shadow: 32px 36px 50px -51px rgba(0, 0, 0, 0.58);
  // `;
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppContainer>
        <HeaderContainer>
          <Header />
        </HeaderContainer>
        <Main>
          <h2>M2</h2>
          <MembersList />
          <Divider />
          <h2>M1</h2>
          <MembersList />
          <h2>B4</h2>
          <MembersList />
          <h2>B3</h2>
          <MembersList />
          <h2>B2</h2>
          <MembersList />
        </Main>
      </AppContainer>
    </div>
  );
}
